sbus_bridge_node:
  ros__parameters:
    port: "/dev/ttyTHS2"
    refresh_rate_hz: 5
    rxMinValue: 172
    rxMaxValue: 1811
    outMinValue: 0
    outMaxValue: 255
    silentOnFailsafe: false
    enableChannelNum: -1
    enableChannelProportionalMin: -1.0
    enableChannelProportionalMax: -1.0